apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: PostgreSQL
    uid: postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: tutorial
    editable: false
    secureJsonData:
      password: $__env{POSTGRES_PASSWORD}
    jsonData:
      database: observability
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
